### ISSUE TITLE
How to link?

### ISSUE THREAD

**Issue by alexandraclaire** [voydz/xamarin-react-native#1]
Hi there,

Firstly, thank you so much for creating this repo, it has been so helpful! 
Secondly, I noticed you wrote a note about linking in your readme. Do you think you could provide a sort of 'instructions for dummies' as to how you would link in this project?

Thanks!

Alex

**Comment by voydz** [comment]
Hi @alexandraclaire,

glad to hear you found this project useful. :)

Unfortunately I am afraid, that the procedure of binding any native plugin, may be very tedious. In fact the binding strategy tends to be very much the same, as in this project. The process would look like this:

1. Create a library binding project using Xamarin (i.e. iOS https://docs.microsoft.com/de-de/xamarin/cross-platform/macios/binding/objective-c-libraries?context=xamarin%2Fios&tabs=vsmac)
2. Make sure every native dependency you need is either already linked natively or installed using a NuGet Package for example (It may be necessary to reference this react-native binding project as well)
3. Make adjustments in the ApiDefinition and StructsAndEnums if necessary
4. Build the project
5. You should get a .dll for each platform (Just like the way the whole ReactNative itself is bound to Mono C# .dll)

Sorry as I can not go into further detail because I am laking time at the moment.
Thanks again for your interest in this project, if you have further questions do not hesitate to ask. I will do my best to answer them ASAP.

best regards

**Comment by alexdunham** [comment]
Hi! 
This was me asking, in my old username.
Thank you for your help!
I wonder if you have any advice for how to update to newer versions of react native? Especially with ios?
I opened an 'issue' about it too.

Thank you!!!

**Comment by voydz** [comment]
for reference, have a look at PR #3
